[tool.poetry]
name = "reconvergentai"
version = "0.1.0"
description = ""
authors = ["basantbhandari <basantbhandari2074@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
